spring:
  application:
    name: alojamientos

server:
  port: ${PORT:8080}

# Configuraci√≥n de Cloudinary
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dygl0ond3}
  api-key: ${CLOUDINARY_API_KEY:355884264733534}
  api-secret: ${CLOUDINARY_API_SECRET:6Ty9-KX9qPI0YpnINa5yPVfn06A}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mySecretKeyForJwtTokenGenerationThatShouldBeVeryLongAndSecure123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz}
  expiration: 8640000

# Logging
logging:
  level:
    com.avanzada.alojamientos: INFO  # Cambiado de DEBUG
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN
    root: INFO  # Cambiado de info
    org.springframework: INFO  # Cambiado de DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true  # IMPORTANTE para Railway
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

mercadopago:
  access:
    token: ${MERCADOPAGO_ACCESS_TOKEN:APP_USR-6031776921093655-100900-11e4ceef9cd55ec049276ca19a7f8a81-2914163040}