spring:
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:admin}

  application:
    name: alojamientos
  datasource:
    url: jdbc:mysql://localhost:3306/alojamientos?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_ROOT_USER:root}
    password: ${MYSQL_ROOT_PASSWORD:admin}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
    open-in-view: false

server:
  port: 8080

# Configuraci√≥n de Cloudinary
cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:dygl0ond3}
  api-key: ${CLOUDINARY_API_KEY:355884264733534}
  api-secret: ${CLOUDINARY_API_SECRET:6Ty9-KX9qPI0YpnINa5yPVfn06A}

# JWT Configuration
jwt:
  secret: mySecretKeyForJwtTokenGenerationThatShouldBeVeryLongAndSecure123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
  expiration: 8640000



# Logging para debugging (opcional)
logging:
  level:
    com.avanzada.alojamientos.security: DEBUG
    com.avanzada.alojamientos.services: DEBUG
    org.springframework.security: DEBUG

mercadopago:
  access:
    token: APP_USR-6031776921093655-100900-11e4ceef9cd55ec049276ca19a7f8a81-2914163040